# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "royce-tf-state"
    dynamodb_table = "royce-tf-lock"
    encrypt        = true
    key            = "base/terraform.tfstate"
    profile        = "royce"
    region         = "eu-west-1"
  }
}
