output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}


## to be passed to the next module

data "aws_eks_cluster" "eks" {
  name = module.eks.cluster_id
}

output "eks_endpoint" {
  value = data.aws_eks_cluster.eks.endpoint
  description = "k8s endpoint"
}

output "eks_certificate" {
  value = base64decode(data.aws_eks_cluster.eks.certificate_authority[0].data)
  sensitive = true
  description = "K8s certificate"
}

data "aws_eks_cluster_auth" "eks" {
  name = module.eks.cluster_id
}

output "eks_token" {
  value = data.aws_eks_cluster_auth.eks.token
  sensitive = true
  description = "K8s token"
}